extends:
  - mysticatea
  - mysticatea/modules
  - plugin:prettier/recommended

rules:
  class-methods-use-this: off
  complexity: off
  no-extend-native: off
  mysticatea/arrow-parens: off
  mysticatea/prefer-for-of: off
  prettier/prettier:
    - error
    - tabWidth: 4
      semi: false
      trailingComma: all
      parser: typescript

overrides:
  - files: ["*.ts"]
    parser: typescript-eslint-parser
    rules:
      lines-between-class-members: off
      init-declarations: off
      no-invalid-this: off
      no-loop-func: off
      no-undef: off
      no-unused-vars: off
      no-use-before-define: off
      no-useless-constructor: off
      require-jsdoc: off
      valid-jsdoc: off
    settings:
      node:
        tryExtensions: [".ts"]
